pipeline{
    agent { label 'electronix'}

    stages{
        stage("I am from elecronix"){
            steps {echo "Hello from Elecronix"}
        }

    stage("I am from elecronix Setup"){
            steps {echo "Elecronix Setup is Working "}
        }
    }    
}