pipeline {
    agent { 
        label 'electronix' 
    }

    environment {
        S3_BUCKET = 'electronix-production-01'
        CLOUDFRONT_ID = 'E1YW0HS96YMVZM'
        AWS_REGION = 'us-east-1'
    }

    stages {

        stage('Frontend Deployment') {

            stages {

                stage('Install Dependencies') {
                    steps {
                        dir('frontend') {
                            sh '''
                                npm install
                            '''
                        }
                    }
                }

                stage('Run Tests') {
                    steps {
                        dir('ecommerce-react-python/frontend') {
                            sh '''
                                npm test -- --watchAll=false || echo "No Test Configured."
                            '''
                        }
                    }
                }

                stage('Build') {
                    steps {
                        dir('ecommerce-react-python/frontend') {
                            sh '''
                                npm run build
                            '''
                        }
                    }
                }

                stage('Deploy S3') {
                    steps {
                        dir('ecommerce-react-python/frontend') {
                            sh '''
                                aws s3 sync dist/ s3://${S3_BUCKET} --delete --region ${AWS_REGION}
                            '''
                        }
                    }
                }

                stage('Invalidation CloudFront Cache') {
                    steps {
                        sh '''
                            aws cloudfront create-invalidation \
                            --distribution-id ${CLOUDFRONT_ID} \
                            --paths "/*"
                        '''
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Frontend Deployment Successful ✅'
        }

        failure {
            echo 'Frontend Deployment Failed ❌'
        }
    }
}
